//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogBook.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicSessions
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int RefClinicsId { get; set; }
        public int UsersId { get; set; }
    
        public virtual RefClinics RefClinic { get; set; }
    }
}
