//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogBook.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefClinics
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
